/* eslint-disable react/no-unescaped-entities */
import Image from 'next/image'
import { Carousel } from 'flowbite-react'
import { Container } from './Container'

import { H1 } from './H1'
import { PiCaretLeftLight, PiCaretRightLight } from 'react-icons/pi'

import imageLiqBack from '../images/projects/liqback.svg';
import imageBrocSwap from '../images/projects/brocswap.svg';
import imageDAO from '../images/projects/dao.svg';
import imageBridge from '../images/projects/bridge.svg';

const Slide = (props: {
    logo: string;
    nameGreen: string
    nameOrange: string
    text: string
}) => {
    return (
        <div className="sm:px-20 h-full">
            <div className="border-2 rounded-xl border-activeblue bg-darkerblue flex flex-col h-full items-center justify-start p-5 pb-12">
                <div className="flex gap-1 items-center mb-5">
                    <Image
                        alt={`${props.nameGreen} ${props.nameOrange}`}
                        src={props.logo}
                        height={32}
                    />
                    <span className="font-title text-xl sm:text-3xl uppercase font-bold text-techGreen">{props.nameGreen}</span>
                    <span className="font-title text-xl sm:text-3xl uppercase font-bold text-degenOrange">{props.nameOrange}</span>
                </div>
                {props.text}
            </div>
        </div>
    )
}

export function Projects() {
    return (
        <Container className="pt-10 pb-10 text-center" id="ecosystem">
            <div className="text-center">
                <H1 className="">
                    <span className="text-techGreen">Explore</span> our ecosystem
                </H1>
                <p className="text-light-600">Our present and future products and services for both projects and users</p>
            </div>

            <div className="h-auto mt-5">
                <Carousel
                    leftControl={<div className="hidden sm:block bg-darkerblue cursor-pointer border-2 border-activeblue rounded-full p-3 hover:bg-dark">
                        <PiCaretLeftLight />
                    </div>}
                    rightControl={<div className="hidden sm:block bg-darkerblue cursor-pointer border-2 border-activeblue rounded-full p-3 hover:bg-dark">
                        <PiCaretRightLight />
                    </div>}
                    indicators
                    theme={{
                        indicators: {
                            active: {
                                off: 'bg-darkblue',
                                on: 'bg-activeblue',
                            },
                        }
                    }}
                >
                    <Slide
                        logo={imageLiqBack}
                        nameGreen="liquidity"
                        nameOrange="backing"
                        text="Liquidity Backing is a feature that creates a secondary asset pool, separate to the regular exchange liquidity pools. With every buy and sell transaction, a portion of the transaction tax flows into the Liquidity Backing pool. Revenue generated by our other products and services will also partially fund Liquidity Backing. Claim Your Share: Burn your tokens to unlock and get your portion instantly. Maximise Profits: Spot arbitrage opportunities for bigger gains!"
                    />
                    <Slide
                        logo={imageBrocSwap}
                        nameGreen="broccoli"
                        nameOrange="swap"
                        text="Broccoliswap is the easiest to use multi-chain swap aggregator. Without any effort, bridge any token from any supported chain to any other supported chain. Includes automatic slippage calculation, token tax calculation, bridging (without constant network switching). A tiny swap fee is taken that is sent to our liquidity backing and upcoming staking pools."
                    />
                    <Slide
                        logo={imageDAO}
                        nameGreen="dao"
                        nameOrange=""
                        text="DegenX is a DAO at heart. All contracts are owned by the DAO. This means that even changing our token tax can only be done by passing a vote. This should give you trust that no single person has control over the project."
                    />
                    <Slide
                        logo={imageBridge}
                        nameGreen="link"
                        nameOrange="bridge"
                        text="Our upcoming bridge will bridge DGNX from AVAX to BSC and ETH. Not only is it a token bridge, our custom built contracts will also transfer DAO decisions to other chains. The bridge will be natively integrated into our other products for seamless interaction on every supported chain."
                    />
                </Carousel>
            </div>
        </Container>
    )
}
