---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Serve password protected development state of the DEGENX Ecosystem dapp through AWS"

Parameters:
  # Base64UserPass:
  #   Type: String
  #   NoEcho: true
  CustomBucketName:
    Type: String
    NoEcho: true

Resources:
  DAPPWIPBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref CustomBucketName
      AccessControl: Private
  DAPPWIPBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref DAPPWIPBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: 's3:GetObject'
            Resource: !Sub "${DAPPWIPBucket.Arn}/*"
            # CF Distribution ARNs have to be manually constructed
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DAPPWIPDistribution}"
  DAPPWIPDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          # Use regional, rather than global, domain for S3 bucket.
          - DomainName: !GetAtt DAPPWIPBucket.RegionalDomainName
            Id: DAPPWIPBucketWebsite                    
            S3OriginConfig:
              OriginAccessIdentity: "" # necessary
            OriginAccessControlId: !GetAtt DAPPWIPOriginAccessControl.Id
        Enabled: true
        DefaultRootObject: index.html
        CustomErrorResponses:
          # when there's a 403 error in the S3 origin, it means that the file is not found
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          # Default cache policy to disable caching.
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          TargetOriginId: DAPPWIPBucketWebsite
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          Compress: true
          # Enforce HTTPS only
          ViewerProtocolPolicy: redirect-to-https
          # FunctionAssociations:
          #   - EventType: viewer-request
          #     FunctionARN: !GetAtt DAPPWIPAuthFunc.FunctionMetadata.FunctionARN
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt DAPPWIPDeepLinkRedirectFunc.FunctionMetadata.FunctionARN
        PriceClass: PriceClass_100
  DAPPWIPOriginAccessControl:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'OAC-${CustomBucketName}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  DAPPWIPDeepLinkRedirectFunc:
    Type: "AWS::CloudFront::Function"
    Properties:
      AutoPublish: true
      FunctionCode: !Sub "
        async function handler(event) {
          const request = event.request; 
          const uri = request.uri;
          if (uri && (uri.match(/dapp$/) || uri.match(/dapp\\//))) request.uri = `/dapp/index.html`; 
          return request;
        }"
      FunctionConfig:
        Comment: "Deep Link Redirect to CloudFront"
        Runtime: cloudfront-js-2.0
      Name: !Sub 'DeepLinkRedirect-${CustomBucketName}'

  # DAPPWIPAuthFunc:
  #   Type: "AWS::CloudFront::Function"
  #   Properties:
  #     AutoPublish: true
  #     FunctionCode: !Sub "
  #       function handler(event) {
  #         var authHeaders = event.request.headers.authorization;
  #         var expected = 'Basic ${Base64UserPass}';

  #         if (authHeaders && authHeaders.value === expected) {
  #           return event.request;
  #         }

  #         var response = {
  #           statusCode: 401,
  #           statusDescription: 'Unauthorized',
  #           headers: {
  #             'www-authenticate': {
  #               value: 'Basic realm=\"Enter credentials\"',
  #             },
  #           },
  #         };
  #         return response;
  #       }"
  #     FunctionConfig:
  #       Comment: "Add HTTP Basic authentication to CloudFront"
  #       Runtime: cloudfront-js-1.0
  #     Name: !Sub 'AuthFn-${CustomBucketName}'

Outputs:
  StaticWebsiteHostname:
    Value: !GetAtt DAPPWIPDistribution.DomainName